export const noSliderBar: string;
export const noSliderBarList: string;
export const slickList: string;
export const slickSlide: string;
export const sliderBar: string;
export const sliderBarArrows: string;
export const sliderBarTitle: string;
export const sliderBarTitleBar: string;
export const sliderBarTitleImg: string;
